blank_issues_enabled: false
contact_links:
  - name: Adwaita for Steam
    url: https://github.com/tkashkin/Adwaita-for-Steam/issues
    about: Please report issues with the theme here. (e.g. The theme is visually broken somehow)
